### PR TITLE
feat: migrate vite-plugin-vue2 to use vue-template-babel-compiler

### PR DESCRIPTION
**Pull request by NikhilVerma**
This allows it to use the modern ES nullish coalescing operators like syntaxes. This changeset is heavily borrowed from https://github.com/pedro-gilmora/vite-vue2

- Several packages have been updated to their recent versions to ensure this changeset works with them.
- Aded playground for the new operators
- Added tsconfig for playground so editors can work with it

### CODE REVIEW

**Comment by Dwight-D** [comment]
Nice work, I'd like to see this implemented as well. 

May I suggest requesting a review from one of the maintainers to hopefully get them to take a look?

**Comment by meduzen** [comment]
@antfu Hello! Any reason why the release that includes this PR has been tagged 2.0 instead of 1.10? The [changelog](https://github.com/underfin/vite-plugin-vue2/blob/master/CHANGELOG.md) doesn’t mention any breaking. 👀

**Comment by antfu** [comment]
Yes, there is no breaking. I just want to make it safer and awarable.

**Comment by NikhilVerma** [comment]
Thank you!

**Pull request merged**
