### PR TITLE
fix: support jsx script blocks within sfc

### PR DESCRIPTION
**Pull request by danielroe**
closes https://github.com/nuxt/vite/issues/82

### CODE REVIEW

**Comment by shoo-be-doo** [comment]
This change prevents the SFC from using JSX.

iShot2021-03-16 10 53 09

**Comment by shoo-be-doo** [comment]
@underfin

**Comment by danielroe** [comment]
@shoo-be-doo Could you provide a reproduction? Are you using `lang="jsx"`?

**Comment by shoo-be-doo** [comment]
I use. The parameter id ends with `lang.jsx`.
The problem is `!query.vue` , in the SFC, `query.vue` always `true`, but `!query.vue` is `false`, so it can't transform vue jsx code.

**Comment by danielroe** [comment]
@shoo-be-doo Could you provide a reproduction? Did your code work before this PR was merged?

**Comment by underfin** [comment]
@danielroe. I fallback this change and I will fix original issue from nuxt-vite.

**Comment by underfin** [comment]
@danielroe. It is a  merge sourcemap  bug at vite core. It already fixed, please upgrade vite version.

**Pull request merged**
